# adityan.dev — the site is built from source here, then served by nginx with
# the SEO 301 redirects baked in.
# Build:  docker build -t adityan-dev .
# Run:    docker run -p 8080:8001 adityan-dev
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY security-headers.conf /etc/nginx/snippets/security-headers.conf
# Generated by the build from scripts/redirects.mjs. NOT in conf.d/ — the base
# image globs conf.d/*.conf at http{} level, where location directives are
# illegal. Snippets are only pulled in explicitly by default.conf.
COPY --from=build /app/nginx-redirects.conf /etc/nginx/snippets/nginx-redirects.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8001
