// The 301s, once. Two things consume this table: the build, which emits
// nginx-redirects.conf for the production image, and scripts/dev.mjs, which
// applies the same rules in the dev server. A redirect is added here and
// nowhere else.
//
// `kind` is the nginx location type, and it also fixes the matching order:
// nginx tries exact matches, then `^~` prefixes, then regexes in order, then
// plain prefixes. MATCH_ORDER below encodes that so the dev server agrees.
//
//   exact   location = /x        the literal path
//   regex   location ~ ^/x$      a regex, with $1.. available in the target
//   block   location ^~ /x/      a prefix that wins over any regex
//   prefix  location /x/         a prefix that regexes are tried before
export const redirects = [
  // --- canonical URL form enforcement ---
  // The site's <link rel="canonical"> tags and sitemap.xml all use the
  // extensionless form. If nginx also serves the old .html paths without
  // redirecting, Google indexes two URLs per page with colliding signals.
  {
    kind: 'exact',
    from: '/index.html',
    to: '/',
    section: 'canonical URL form enforcement',
    note: '/index.html is the same resource as /',
  },
  {
    kind: 'regex',
    from: '^/(about|projects|blog|contact)\\.html$',
    to: '/$1',
    note: 'old .html core pages -> extensionless canonicals',
  },
  {
    kind: 'regex',
    from: '^/blog/([a-z0-9-]+)\\.html$',
    to: '/blog/$1',
    note: 'old .html blog posts. A regex, so posts added later are covered too.',
  },

  { kind: 'exact', from: '/about/', to: '/about', section: 'old Hugo site -> new site' },
  { kind: 'exact', from: '/projects/', to: '/projects' },
  { kind: 'exact', from: '/posts/', to: '/blog' },
  {
    kind: 'regex',
    from: '^/posts/([a-z0-9-]+)/?$',
    to: '/blog/$1',
    note: 'blog posts: old /posts/<slug>/ -> new /blog/<slug>',
  },

  { kind: 'block', from: '/tags/', to: '/blog', section: 'taxonomy pages that no longer exist -> the blog index' },
  { kind: 'block', from: '/categories/', to: '/blog' },
  { kind: 'block', from: '/authors/', to: '/blog' },
  { kind: 'block', from: '/series/', to: '/blog' },

  {
    kind: 'prefix',
    from: '/posts/',
    to: '/blog',
    note: 'Safety net: any other /posts/* the regex above did not match.',
  },
];

// nginx's location precedence, as an evaluation order for consumers that do not
// have it built in.
const MATCH_ORDER = ['exact', 'block', 'regex', 'prefix'];

// Each rule as a JS RegExp over the request path, ordered the way nginx would
// resolve them. `to` is a String.replace target, so $1 works unchanged.
export const matchers = [...redirects]
  .sort((a, b) => MATCH_ORDER.indexOf(a.kind) - MATCH_ORDER.indexOf(b.kind))
  .map(({ kind, from, to }) => ({
    pattern:
      kind === 'regex'
        ? new RegExp(from)
        : new RegExp(`^${escape(from)}${kind === 'exact' ? '' : '.*'}$`),
    to,
  }));

function escape(literal) {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const LOCATION = { exact: '= ', regex: '~ ', block: '^~ ', prefix: '' };

const HEADER = `# ---------------------------------------------------------------------------
# GENERATED by scripts/redirects.mjs — do not edit. Run \`npm run build\`.
#
# 301 redirects: OLD Hugo site URLs AND the old .html URLs -> NEW clean URLs.
#
# The previous adityan.dev (Hugo) used /about/, /posts/<slug>/, /tags/... etc.
# Before that, this site used /about.html, /blog/<slug>.html. The canonical
# form is now the extensionless route (/about, /blog/<slug>). Without these
# redirects, every URL Google has indexed becomes a 404 and loses its ranking
# history. A 301 passes ~all of that signal to the new URL.
#
# The Dockerfile installs this at /etc/nginx/snippets/ and default.conf
# includes it inside its \`server { }\`.
# ---------------------------------------------------------------------------
`;

export const nginxConf = () =>
  redirects
    .map(({ kind, from, to, section, note }) =>
      [
        section ? `\n# --- ${section} ---` : null,
        note ? `${section ? '' : '\n'}# ${note}` : null,
        `location ${LOCATION[kind]}${from} { return 301 ${to}; }`,
      ]
        .filter(Boolean)
        .join('\n')
    )
    .reduce((conf, block) => `${conf}${block}\n`, HEADER);
